// Copyright 2019, Keychain Foundation Ltd.
// This file is part of the dipperin-core library.
//
// The dipperin-core library is free software: you can redistribute
// it and/or modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The dipperin-core library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/dipperin/dipperin-core/core/chain-communication (interfaces: NodeConf)

// Package chain_communication is a generated GoMock package.
package chain_communication

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockNodeConf is a mock of NodeConf interface
type MockNodeConf struct {
	ctrl     *gomock.Controller
	recorder *MockNodeConfMockRecorder
}

// MockNodeConfMockRecorder is the mock recorder for MockNodeConf
type MockNodeConfMockRecorder struct {
	mock *MockNodeConf
}

// NewMockNodeConf creates a new mock instance
func NewMockNodeConf(ctrl *gomock.Controller) *MockNodeConf {
	mock := &MockNodeConf{ctrl: ctrl}
	mock.recorder = &MockNodeConfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNodeConf) EXPECT() *MockNodeConfMockRecorder {
	return m.recorder
}

// GetNodeName mocks base method
func (m *MockNodeConf) GetNodeName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNodeName indicates an expected call of GetNodeName
func (mr *MockNodeConfMockRecorder) GetNodeName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeName", reflect.TypeOf((*MockNodeConf)(nil).GetNodeName))
}

// GetNodeType mocks base method
func (m *MockNodeConf) GetNodeType() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeType")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetNodeType indicates an expected call of GetNodeType
func (mr *MockNodeConfMockRecorder) GetNodeType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeType", reflect.TypeOf((*MockNodeConf)(nil).GetNodeType))
}
