// Copyright 2019, Keychain Foundation Ltd.
// This file is part of the dipperin-core library.
//
// The dipperin-core library is free software: you can redistribute
// it and/or modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The dipperin-core library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/dipperin/dipperin-core/core/chain-communication (interfaces: VerifiersReader)

// Package chain_communication is a generated GoMock package.
package chain_communication

import (
	common "github.com/dipperin/dipperin-core/common"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockVerifiersReader is a mock of VerifiersReader interface
type MockVerifiersReader struct {
	ctrl     *gomock.Controller
	recorder *MockVerifiersReaderMockRecorder
}

// MockVerifiersReaderMockRecorder is the mock recorder for MockVerifiersReader
type MockVerifiersReaderMockRecorder struct {
	mock *MockVerifiersReader
}

// NewMockVerifiersReader creates a new mock instance
func NewMockVerifiersReader(ctrl *gomock.Controller) *MockVerifiersReader {
	mock := &MockVerifiersReader{ctrl: ctrl}
	mock.recorder = &MockVerifiersReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockVerifiersReader) EXPECT() *MockVerifiersReaderMockRecorder {
	return m.recorder
}

// CurrentVerifiers mocks base method
func (m *MockVerifiersReader) CurrentVerifiers() []common.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentVerifiers")
	ret0, _ := ret[0].([]common.Address)
	return ret0
}

// CurrentVerifiers indicates an expected call of CurrentVerifiers
func (mr *MockVerifiersReaderMockRecorder) CurrentVerifiers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentVerifiers", reflect.TypeOf((*MockVerifiersReader)(nil).CurrentVerifiers))
}

// NextVerifiers mocks base method
func (m *MockVerifiersReader) NextVerifiers() []common.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextVerifiers")
	ret0, _ := ret[0].([]common.Address)
	return ret0
}

// NextVerifiers indicates an expected call of NextVerifiers
func (mr *MockVerifiersReaderMockRecorder) NextVerifiers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextVerifiers", reflect.TypeOf((*MockVerifiersReader)(nil).NextVerifiers))
}

// ShouldChangeVerifier mocks base method
func (m *MockVerifiersReader) ShouldChangeVerifier() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldChangeVerifier")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldChangeVerifier indicates an expected call of ShouldChangeVerifier
func (mr *MockVerifiersReaderMockRecorder) ShouldChangeVerifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldChangeVerifier", reflect.TypeOf((*MockVerifiersReader)(nil).ShouldChangeVerifier))
}
