// Copyright 2019, Keychain Foundation Ltd.
// This file is part of the dipperin-core library.
//
// The dipperin-core library is free software: you can redistribute
// it and/or modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The dipperin-core library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by "stringer -type=VoteMsgType"; DO NOT EDIT.

package model

import "strconv"

const _VoteMsgType_name = "PreVoteMessageVoteMessageVerBootNodeVoteMessageAliveVerifierVoteMessage"

var _VoteMsgType_index = [...]uint8{0, 14, 25, 47, 71}

func (i VoteMsgType) String() string {
	if i >= VoteMsgType(len(_VoteMsgType_index)-1) {
		return "VoteMsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VoteMsgType_name[_VoteMsgType_index[i]:_VoteMsgType_index[i+1]]
}
