// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dipperin/dipperin-core/core/chaincommunication (interfaces: P2PServer)

// Package chaincommunication is a generated GoMock package.
package chaincommunication

import (
	enode "github.com/dipperin/dipperin-core/third_party/p2p/enode"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockP2PServer is a mock of P2PServer interface
type MockP2PServer struct {
	ctrl     *gomock.Controller
	recorder *MockP2PServerMockRecorder
}

// MockP2PServerMockRecorder is the mock recorder for MockP2PServer
type MockP2PServerMockRecorder struct {
	mock *MockP2PServer
}

// NewMockP2PServer creates a new mock instance
func NewMockP2PServer(ctrl *gomock.Controller) *MockP2PServer {
	mock := &MockP2PServer{ctrl: ctrl}
	mock.recorder = &MockP2PServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockP2PServer) EXPECT() *MockP2PServerMockRecorder {
	return m.recorder
}

// AddPeer mocks base method
func (m *MockP2PServer) AddPeer(arg0 *enode.Node) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPeer", arg0)
}

// AddPeer indicates an expected call of AddPeer
func (mr *MockP2PServerMockRecorder) AddPeer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPeer", reflect.TypeOf((*MockP2PServer)(nil).AddPeer), arg0)
}

// RemovePeer mocks base method
func (m *MockP2PServer) RemovePeer(arg0 *enode.Node) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemovePeer", arg0)
}

// RemovePeer indicates an expected call of RemovePeer
func (mr *MockP2PServerMockRecorder) RemovePeer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePeer", reflect.TypeOf((*MockP2PServer)(nil).RemovePeer), arg0)
}

// Self mocks base method
func (m *MockP2PServer) Self() *enode.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Self")
	ret0, _ := ret[0].(*enode.Node)
	return ret0
}

// Self indicates an expected call of Self
func (mr *MockP2PServerMockRecorder) Self() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Self", reflect.TypeOf((*MockP2PServer)(nil).Self))
}
