// Copyright 2019, Keychain Foundation Ltd.
// This file is part of the dipperin-core library.
//
// The dipperin-core library is free software: you can redistribute
// it and/or modify it under the terms of the GNU Lesser General Public License
// as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// The dipperin-core library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/caiqingfeng/dipperin-core/core/verifiers-halt-check (interfaces: CsProtocolFunction)

// Package verifiers_halt_check is a generated GoMock package.
package verifiers_halt_check

import (
	chain_communication "github.com/dipperin/dipperin-core/core/chain-communication"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCsProtocolFunction is a mock of CsProtocolFunction interface
type MockCsProtocolFunction struct {
	ctrl     *gomock.Controller
	recorder *MockCsProtocolFunctionMockRecorder
}

// MockCsProtocolFunctionMockRecorder is the mock recorder for MockCsProtocolFunction
type MockCsProtocolFunctionMockRecorder struct {
	mock *MockCsProtocolFunction
}

// NewMockCsProtocolFunction creates a new mock instance
func NewMockCsProtocolFunction(ctrl *gomock.Controller) *MockCsProtocolFunction {
	mock := &MockCsProtocolFunction{ctrl: ctrl}
	mock.recorder = &MockCsProtocolFunctionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCsProtocolFunction) EXPECT() *MockCsProtocolFunctionMockRecorder {
	return m.recorder
}

// GetCurrentVerifierPeers mocks base method
func (m *MockCsProtocolFunction) GetCurrentVerifierPeers() map[string]chain_communication.PmAbstractPeer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentVerifierPeers")
	ret0, _ := ret[0].(map[string]chain_communication.PmAbstractPeer)
	return ret0
}

// GetCurrentVerifierPeers indicates an expected call of GetCurrentVerifierPeers
func (mr *MockCsProtocolFunctionMockRecorder) GetCurrentVerifierPeers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentVerifierPeers", reflect.TypeOf((*MockCsProtocolFunction)(nil).GetCurrentVerifierPeers))
}

// GetNextVerifierPeers mocks base method
func (m *MockCsProtocolFunction) GetNextVerifierPeers() map[string]chain_communication.PmAbstractPeer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextVerifierPeers")
	ret0, _ := ret[0].(map[string]chain_communication.PmAbstractPeer)
	return ret0
}

// GetNextVerifierPeers indicates an expected call of GetNextVerifierPeers
func (mr *MockCsProtocolFunctionMockRecorder) GetNextVerifierPeers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextVerifierPeers", reflect.TypeOf((*MockCsProtocolFunction)(nil).GetNextVerifierPeers))
}

// GetVerifierBootNode mocks base method
func (m *MockCsProtocolFunction) GetVerifierBootNode() map[string]chain_communication.PmAbstractPeer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerifierBootNode")
	ret0, _ := ret[0].(map[string]chain_communication.PmAbstractPeer)
	return ret0
}

// GetVerifierBootNode indicates an expected call of GetVerifierBootNode
func (mr *MockCsProtocolFunctionMockRecorder) GetVerifierBootNode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerifierBootNode", reflect.TypeOf((*MockCsProtocolFunction)(nil).GetVerifierBootNode))
}
